import { Product } from '@/types/product';

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    title: 'Creator Starter Kit',
    description: 'Everything you need to start your creator business. Includes templates, checklists, and guides.',
    price: 29,
    images: ['/images/product-1.jpg'],
    files: ['/files/starter-kit.zip'],
    category: 'template',
    featured: true,
    published: true,
    salesCount: 142,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-01'),
    creatorId: 'ghost-user-id',
  },
  {
    id: 'prod-2',
    title: 'Content Strategy Guide',
    description: 'A comprehensive guide to building a content strategy that grows your audience and revenue.',
    price: 49,
    images: ['/images/product-2.jpg'],
    files: ['/files/content-strategy.pdf'],
    category: 'ebook',
    featured: true,
    published: true,
    salesCount: 89,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-05'),
    creatorId: 'ghost-user-id',
  },
  {
    id: 'prod-3',
    title: 'Email Templates Pack',
    description: '50+ proven email templates for creators. Welcome sequences, sales emails, newsletters, and more.',
    price: 19,
    images: ['/images/product-3.jpg'],
    files: ['/files/email-templates.zip'],
    category: 'template',
    featured: false,
    published: true,
    salesCount: 234,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-10'),
    creatorId: 'ghost-user-id',
  },
  {
    id: 'prod-4',
    title: 'Thumbnail Design Pack',
    description: '100+ customizable thumbnail templates for YouTube, courses, and social media.',
    price: 15,
    images: ['/images/product-4.jpg'],
    files: ['/files/thumbnails.zip'],
    category: 'template',
    featured: false,
    published: true,
    salesCount: 312,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-20'),
    creatorId: 'ghost-user-id',
  },
  {
    id: 'prod-5',
    title: 'Social Media Presets',
    description: 'Professional Lightroom presets optimized for social media photos.',
    price: 25,
    images: ['/images/product-5.jpg'],
    files: ['/files/presets.zip'],
    category: 'preset',
    featured: false,
    published: false,
    salesCount: 0,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
    creatorId: 'ghost-user-id',
  },
];
